services:
  - type: web
    name: krishvya-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: "file:./prisma/dev.db"
      - key: JWT_SECRET
        generateValue: true
